// File lang/cpp/src/messages/TIM.h
// Auto-generated by pyUBX generateCpp.py v0.1 on 2020-03-01T13:29:34.883975
// See https://github.com/mayeranalytics/pyUBX
// DO NOT MODIFY THIS FILE!

#ifndef __TIM_H__
#define __TIM_H__

#include <stdint.h>
#include "../UBX.h"

/* Message class TIM.
 */
struct TIM
{
    struct SVIN;
};

struct TIM::SVIN : public Message
{
    uint32_t dur;
    int32_t meanX;
    int32_t meanY;
    int32_t meanZ;
    uint32_t meanV;
    uint32_t obs;
    uint8_t valid;
    uint8_t active;
    uint16_t reserved;

    static uint8_t classID;
    static uint8_t messageID;
};

uint8_t TIM::SVIN::classID   = 0x0D;
uint8_t TIM::SVIN::messageID = 0x04;

#endif // ifndef __TIM_H__
